module.exports = {
	'ahri': 'Ahri',
	'akali': 'Akali',
	'alistar': 'Alistar',
	'amumu': 'Amumu',
	'annie': 'Annie',
	'ashe': 'Ashe',
	'aurelionsol': 'Aurelion Sol',
	'blitzcrank': 'Blitzcrank',
	'braum': 'Braum',
	'camille': 'Camille',
	'corki': 'Corki',
	'darius': 'Darius',
	'diana': 'Diana',
	'drmundo': 'Dr. Mundo',
	'draven': 'Draven',
	'evelynn': 'Evelynn',
	'ezreal': 'Ezreal',
	'fiora': 'Fiora',
	'fizz': 'Fizz',
	'galio': 'Galio',
	'garen': 'Garen',
	'gragas': 'Gragas',
	'graves': 'Graves',
	'janna': 'Janna',
	'jarvaniv': 'Jarvan IV',
	'jax': 'Jax',
	'jhin': 'Jhin',
	'jinx': 'Jinx',
	'kaisa': "Kai'sa",
	'katarina': 'Katarina',
	'kennen': 'Kennen',
	'leesin': 'Lee Sin',
	'leona': 'Leona',
	'lulu': 'Lulu',
	'lux': 'Lux',
	'malphite': 'Malphite',
	'masteryi': 'Master Yi',
	'missfortune': 'Miss Fortune',
	'nami': 'Nami',
	'nasus': 'Nasus',
	'olaf': 'Olaf',
	'orianna': 'Orianna',
	'pantheon': 'Pantheon',
	'rakan': 'Rakan',
	'seraphine': 'Seraphine',
	'shyvana': 'Shyvana',
	'singed': 'Singed',
	'sona': 'Sona',
	'soraka': 'Soraka',
	'teemo': 'Teemo',
	'tristana': 'Tristana',
	'tryndamere': 'Tryndamere',
	'twistedfate': 'Twisted Fate',
	'varus': 'Varus',
	'vayne': 'Vayne',
	'vi': 'Vi',
	'wukong': 'Wukong',
	'xayah': 'Xayah',
	'xinzhao': 'Xin Zhao',
	'yasuo': 'Yasuo',
	'zed': 'Zed',
	'ziggs': 'Ziggs',
}