const {
	REACT_APP_CLIENT_URL,
	REACT_APP_SERVER_URL,
	REACT_APP_RECAPTCHA_PUBLIC_KEY,
	REACT_APP_FIREBASE_API_KEY,
	REACT_APP_FIREBASE_AUTH_DOMAIN,
	REACT_APP_FIREBASE_PROJECT_ID,
	REACT_APP_FIREBASE_STORAGE_BUCKET,
	REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
	REACT_APP_FIREBASE_APP_ID,
	REACT_APP_FIREBASE_MEASUREMENT_ID,
} = process.env;

export const URL = {
	CLIENT: REACT_APP_CLIENT_URL,
	SERVER: REACT_APP_SERVER_URL,
};

export const ReCaptcha = {
	PUBLIC_KEY: REACT_APP_RECAPTCHA_PUBLIC_KEY,
};

export const Firebase = {
	apiKey: REACT_APP_FIREBASE_API_KEY,
	authDomain: REACT_APP_FIREBASE_AUTH_DOMAIN,
	projectId: REACT_APP_FIREBASE_PROJECT_ID,
	storageBucket: REACT_APP_FIREBASE_STORAGE_BUCKET,
	messagingSenderId: REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
	appId: REACT_APP_FIREBASE_APP_ID,
	measurementId: REACT_APP_FIREBASE_MEASUREMENT_ID,
};
