
// === GAME DATA === //
const GAMEDATA_SET_CHAMPIONS = 'GAMEDATA_SET_CHAMPIONS';
const GAMEDATA_SET_ITEMS = 'GAMEDATA_SET_ITEMS';
const GAMEDATA_SET_RANKS = 'GAMEDATA_SET_RANKS';
const GAMEDATA_SET_ROLES = 'GAMEDATA_SET_ROLES';
const GAMEDATA_SET_RUNES = 'GAMEDATA_SET_RUNES';
const GAMEDATA_SET_SPELLS = 'GAMEDATA_SET_SPELLS';

// === BUILD === //
const BUILD_SET_BUILDTITLE = 'BUILD_SET_BUILDTITLE';
const BUILD_SET_BUILDROLE = 'BUILD_SET_BUILDROLE';
const BUILD_SET_BUILDS = 'BUILD_SET_BUILDS';
const BUILD_SET_CHAMPIONSELECTED = 'BUILD_SET_CHAMPIONSELECTED';
const BUILD_SET_DESCRIPTION = 'BUILD_SET_DESCRIPTION';
const BUILD_SET_GAMEMODE = 'BUILD_SET_GAMEMODE';
const BUILD_SET_ITEMSCONFIRMED = 'BUILD_SET_ITEMSCONFIRMED';
const BUILD_SET_RANKSELECTED = 'BUILD_SET_RANKSELECTED';
const BUILD_SET_RUNESSELECTED = 'BUILD_SET_RUNESSELECTED';
const BUILD_SET_SERVER = 'BUILD_SET_SERVER';
const BUILD_SET_SPELLSSELECTED = 'BUILD_SET_SPELLSSELECTED';
const BUILD_SET_USERNAME = 'BUILD_SET_USERNAME';
const BUILD_RESET = 'BUILD_RESET';

// === VALIDATION === //
const RECAPTCHA_SET_REF = 'RECAPTCHA_SET_REF';
const RECAPTCHA_SET_TOKEN = 'RECAPTCHA_SET_TOKEN';

// === SNACKBAR === //
const SNACKBAR_SET_CONTROLS = 'SNACKBAR_SET_CONTROLS'

module.exports = {
	// Game Data
	GAMEDATA_SET_CHAMPIONS,
	GAMEDATA_SET_ITEMS,
	GAMEDATA_SET_RANKS,
	GAMEDATA_SET_ROLES,
	GAMEDATA_SET_RUNES,
	GAMEDATA_SET_SPELLS,
	// Build
	BUILD_SET_BUILDTITLE,
	BUILD_SET_BUILDROLE,
	BUILD_SET_BUILDS,
	BUILD_SET_CHAMPIONSELECTED,
	BUILD_SET_DESCRIPTION,
	BUILD_SET_GAMEMODE,
	BUILD_SET_ITEMSCONFIRMED,
	BUILD_SET_RANKSELECTED,
	BUILD_SET_RUNESSELECTED,
	BUILD_SET_SERVER,
	BUILD_SET_SPELLSSELECTED,
	BUILD_SET_USERNAME,
	BUILD_RESET,
	// Validation
	RECAPTCHA_SET_REF,
	RECAPTCHA_SET_TOKEN,
	SNACKBAR_SET_CONTROLS
}