export const GameMode = {
	ARAM: 'aram',
	NORMAL: 'normal',
};

export const GameRegion = {
	SEA: 'sea',
	NA: 'na',
	EUW: 'euw',
};

export const ErrorTypes = {
	FAILED_TO_SAVE_BUILD: 'FAILED_TO_SAVE_BUILD',
	NO_BUILD_TITLE: 'NO_BUILD_TITLE',
	NO_USERNAME: 'NO_USERNAME',
	NOT_VALID_BUILD_TITLE: 'NOT_VALID_BUILD_TITLE',
	NOT_VALID_USERNAME: 'NOT_VALID_USERNAME',
	NOT_VALID_BUILD_DESCRIPTION: 'NOT_VALID_BUILD_DESCRIPTION',
	NOT_VALID_ITEMS_SELECTED: 'NOT_VALID_ITEMS_SELECTED',
	HAS_DUPLICATE_ITEMS: 'HAS_DUPLICATE_ITEMS',
};
